MVCWebApp/Models/ErrorViewModel.cs
namespace MVCWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCWebApp/Models/FileBlob.cs
namespace MVCWebApp.Models
{
    public class FileBlob
    {
        public string? Url { get; set; }
        public string? Name { get; set; }
    }
}

MVCWebApp/Controllers/BlobsController.cs
using System.IO;
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using AzureStorageLibrary;
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;

namespace MVCWebApp.Controllers
{
    public class BlobsController : Controller
    {
        private readonly IBlobStorage _blobStorage;

        public BlobsController(IBlobStorage blobStorage)
        {
            _blobStorage = blobStorage;
        }

        public IActionResult Index()
        {
            var names = _blobStorage.GetNames(EContainerName.pictures);
            var pdfs = _blobStorage.GetNames(EContainerName.pdf);
            string blobUrl = $"{_blobStorage.BlobUrl}/{EContainerName.pictures.ToString()}";
            string blobUrlPdf = $"{_blobStorage.BlobUrl}/{EContainerName.pdf.ToString()}";

            ViewBag.blobs = names.Select(x => new FileBlob { Name = x, Url = $"{blobUrl}/{x}" }).ToList();
            ViewBag.blobsPdf = pdfs.Select(x => new FileBlob { Name = x, Url = $"{blobUrlPdf}/{x}" }).ToList();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile picture)
        {
            var newFileName = Guid.NewGuid().ToString() + Path.GetExtension(picture.FileName);
            await _blobStorage.UploadAsync(picture.OpenReadStream(), newFileName, EContainerName.pictures);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UploadPdf(IFormFile pdf)
        {
            string connectionString = ConnectionStrings.AzureStorageConnectionString; // Gerçek bağlantı dizesi ile değiştirin
            string containerName = EContainerName.pdf.ToString(); // Gerçek konteyner adı ile değiştirin

            string fileName = Path.GetFileName(pdf.FileName);

            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

            BlobClient blobClient = containerClient.GetBlobClient(fileName);

            // Dosyayı Azure Blob Storage'e yükle
            using (Stream stream = pdf.OpenReadStream())
            {
                await blobClient.UploadAsync(stream, true);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Download(string filename)
        {
            var stream = await _blobStorage.DownloadAsync(filename, EContainerName.pictures);
            return File(stream, "application/octet-stream", filename);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string fileName)
        {
            await _blobStorage.DeleteAsync(fileName, EContainerName.pictures);
            return RedirectToAction("Index");
        }


    }
}

MVCWebApp/Controllers/HomeController.cs
using AzureStorageLibrary;
using AzureStorageLibrary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos.Table;
using MVCWebApp.Models;
using System.Diagnostics;
using System.Net;

namespace MVCWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly INoSqlStorage<Product> _noSqlStorage;

        public HomeController(INoSqlStorage<Product> noSqlStorage)
        {
            _noSqlStorage = noSqlStorage;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.products = (await _noSqlStorage.All()).ToList();
            ViewBag.IsUpdate = false;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
            product.RowKey = Guid.NewGuid().ToString();
            product.PartitionKey = "Shoes";

            await _noSqlStorage.Add(product);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(string rowKey, string partitionKey)
        {
            var product = await _noSqlStorage.Get(rowKey, partitionKey);
            ViewBag.products = (await _noSqlStorage.All()).ToList();
            ViewBag.IsUpdate = true;

            return View("Index", product);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Product product)
        {
            ViewBag.IsUpdate = true;
            product.ETag = "*";
            try
            {
                await _noSqlStorage.Update(product);
                return RedirectToAction("Index");

            }
            catch (StorageException ex)
            {
                ex.RequestInformation.HttpStatusCode = (int)HttpStatusCode.PreconditionFailed;
                throw;
            }

        }

        [HttpGet]
        public async Task<IActionResult> Delete(string rowKey, string partitionKey)
        {

            await _noSqlStorage.Delete(rowKey, partitionKey);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Query(int filterPrice)
        {
            ViewBag.IsUpdate = false;
            ViewBag.products = (await _noSqlStorage.Query(x => x.Price > filterPrice)).ToList();
            return View("Index");
        }
    }
}

MVCWebApp/Views/Blobs/Index.cshtml
<h2>
    Save Picture
</h2>

<form asp-action="Upload" method="post" asp-controller="Blobs" enctype="multipart/form-data">
    <input type="file" name="picture" />
    <button class="btn btn-primary" type="submit">Save</button>
</form>

<h2>
    Save Pdf
</h2>

<form asp-action="UploadPdf" method="post" asp-controller="Blobs" enctype="multipart/form-data">
    <input type="file" name="pdf" />
    <button class="btn btn-primary" type="submit">Save</button>
</form>

<h2>
    Pictures
</h2>

<table class="table table-bordered">
    <tr>
        <td>Picture</td>
        <td>Name</td>
        <td>Actions</td>
    </tr>

    @foreach (var item in ViewBag.blobs as List<FileBlob>)
    {
        <tr>
            <td>
                <img src="@item.Url" class="img-thumbnail" style="width:100px;" />
            </td>
            <td>
                @item.Name
            </td>
            <td>
                <a class="btn btn-warning" asp-action="Download" asp-route-filename="@item.Name">Download</a>
                <a class="btn btn-danger" asp-action="Delete" asp-route-filename="@item.Name">Delete</a>
            </td>
        </tr>
    }
</table>

<table class="table table-bordered">
    <tr>
        <td>Name</td>
        <td>Actions</td>
    </tr>

    @foreach (var item in ViewBag.blobsPdf as List<FileBlob>)
    {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                <button onclick="ShowPdf('@item.Url')">Show</button>
            </td>
        </tr>
    }
</table>

<iframe id="showPdf" style="width:200px;height:400px"></iframe>

<script>
    function ShowPdf(pdfUrl) {
        var element = document.getElementById("showPdf");
        element.src = pdfUrl;
    }
</script>

MVCWebApp/Views/Home/Index.cshtml
@using AzureStorageLibrary.Models
@model Product

@{
    ViewData["Title"] = "Home Page";
}

<h2>Add Or Update Product</h2>

<form class="form-inline" asp-action="@(ViewBag.IsUpdate ? "Update" : "Create")" method="post" enctype="application/x-www-form-urlencoded">
    <input  class="form-control mr-1" asp-for="Name" placeholder="Enter Name"/>
    <input  class="form-control mr-1" asp-for="Price" placeholder="Enter Price"/>
    <input  class="form-control mr-1" asp-for="Stock" placeholder="Enter Stock"/>
    <input  class="form-control mr-1" asp-for="Color" placeholder="Enter Color"/>

    <input type="hidden" asp-for="RowKey"/>
    <input type="hidden" asp-for="PartitionKey"/>
    <input type="hidden" asp-for="ETag"/>

    <input class="btn btn-primary" type="submit" value="@(ViewBag.IsUpdate ? "Update Product":"Add new Product")" />
</form>


<h1>Products</h1>

<form class="form-inline" method="get" asp-action="Query">
    <input type="number" name="filterPrice" />
    <input type="submit" class="btn btn-dark" value="Query" />
</form>

<table class="table table-bordered">
    <tr>
        <th>RowKey</th>
        <th>PartitionKey</th>
        <th>Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Color</th>
        <th>TimeStamp</th>
        <th>Actions</th>
        <th>Actions</th>
    </tr>

    @foreach (var item in ViewBag.products as List<Product>)
    {
        <tr>
            <td>
                @item.RowKey
            </td>
            <td>
                @item.PartitionKey
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.Price
            </td>
            <td>
                @item.Stock
            </td>
            <td>
                @item.Color
            </td>
            <td>
                @item.Timestamp
            </td>
            <td>
                <a class="btn btn-danger" asp-action="Update" asp-controller="Home"
                asp-route-rowKey="@item.RowKey" asp-route-partitionKey="@item.PartitionKey"
                >Update</a>
            </td>

            <td>
                <a class="btn btn-danger" asp-action="Delete" asp-controller="Home"
                   asp-route-rowKey="@item.RowKey" asp-route-partitionKey="@item.PartitionKey">Delete</a>
            </td>
        </tr>
    }
</table>

MVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>